# Generated by Django 3.2 on 2022-11-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
