version: '3.9'

services:
  
  db:
    image: postgres:14.5-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: db-name
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: db-password
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
    driver: local
