version: '3.9'

services:
  
  db:
    image: postgres:14.5-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: db-name
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: db-password
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  
  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      CORESETTINGS_DATABASES: '{"default": {"HOST": "db"}}'
      CORESETTINGS_LOCAL_SETTINGS_PATH: 'local/settings.prod.py'

volumes:
  postgresql-data:
    driver: local
