# Generated by Django 3.2 on 2022-12-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwithmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.TextField()),
                ('soft_delete', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
