version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: projvar_blog
      POSTGRES_USER: projvar_blog
      POSTGRES_PASSWORD: projvar_blog
    volumes:
      - postgresql-data: /var/lib/postgresql/data

volumes:
  - postgresql-data:
    driver: local
