# Generated by Django 3.2 on 2022-12-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=100, unique=True)),
                ('throttle', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
    ]
