# Generated by Django 3.2 on 2022-12-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('throttle', '0002_view_viewmemory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewmemory',
            name='view',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_memories', to='throttle.view'),
        ),
    ]
