# Generated by Django 3.2 on 2023-02-17 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('throttle', '0003_alter_viewmemory_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='viewmemory',
            name='view',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='throttle',
        ),
        migrations.AddField(
            model_name='memory',
            name='From',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memory',
            name='hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='View',
        ),
        migrations.DeleteModel(
            name='ViewMemory',
        ),
        migrations.AddField(
            model_name='condition',
            name='limit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='throttle.limit'),
        ),
    ]
