# Generated by Django 3.2 on 2023-02-17 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('throttle', '0004_auto_20230218_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='throttle.condition'),
            preserve_default=False,
        ),
    ]
