# Generated by Django 3.2 on 2022-11-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('line', models.CharField(max_length=100)),
                ('seen', models.IntegerField(default=0)),
            ],
        ),
    ]
